### ISSUE TITLE
Make it work

### ISSUE THREAD

**Issue by 1dolla** [mackonsti/yet-another-nfo-viewer#8]
This program shows the first X lines of an nfo, making it useless.

If it showed the file it opened instead, it would be useful.

Please make it work or remove it from github. Thank you.

**Comment by mackonsti** [comment]
Hello, I am sorry this tool doesn't work for you.

First of all, your message/report/details are incomplete, no sample file provided, no OS, nothing.

Secondly, what do you mean "remove it from github"? Everything you find on GitHub works for you always and 100%?

Moreover, I had stated that I may be the original person behind it but it's been 10 years ago and I have not touched the code. 

Hence why I ask for people/coders to contribute (it is not Swift) and I believe I am allowed to leave this here open for people who want to make it better as a) I no longer have the time, b) no longer have the needed experience.

That is why in my home page I wrote: _Should you wish to contribute, you are very welcome to do so via a [Pull Request](https://github.com/mackonsti/yet-another-nfo-viewer/pulls) that I'd be happy to approve._

So please if this tool does not work well for you, I am sorry, kindly remove it from your Mac instead.

I am not doubting your issue but a) nothing useful was provided, b) I cannot help you. Perhaps @skylex has the time and energy to help, as he/she did in the past, but without information, you would be asked the same questions as myself.

Hope you understand. Thanks for reading.
